### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by azet** [stribika/sshlabs#3]
Hi,

Nice idea. I'm a bit confused to some of the labeling though. Basically every NIST curve is labeled `BULLRUN`. I don't think this is true. HMAC's are labeled with 'weak hash'. Well - It's an HMAC not used as a hash function. You'll need to research if a HMAC construct of a given hash _actually_ means the HMAC is affected with security problems as well. UMACs 64 tag is not really _small_ (compare to other protocols, i.e. TLS). 

Besides that this looks very reasonable. Thanks for the effort.

Aaron

**Comment by stribika** [comment]
NIST: NIST curve parameters were chosen in a way that makes it hard to implement correctly and very easy to make fatal mistakes. Whether that's deliberate or not is debatable. The OpenSSH developers say their implementation is fine and I believe them. What about other implementations? What if a future patch breaks it?

When the curves are used for signing, the ECDSA algorithm is essentially the original ElGamal algorithm, ignoring years of improvements.

HMAC algorithms: I know you don't automatically get an attack on HMAC-SHA1 for every an attack on SHA1. Also, the best attack on SHA1 is a collision and to break MAC you need preimage. Even so, I recommend turning off SHA1 and MD5 support to prevent future/secret attacks.

MAC tag sizes: It does mean you can make a packet in at most 2^64 that will be accepted. That attack may not be realistic in the TCP timeout timeframe but it's best to be on the safe side.

**Comment by azet** [comment]
I agree in principle. The problem being: you want be able to connect to any modern linux system nor embedded device if you remove everything that would be labeled as bad by your script.

**Comment by stribika** [comment]
Sorry, I forgot about this. The labels and scores are much more realistic. You can get 7/10 with NISTP\* + ECDSA, and 8-9/10 with only MAC problems.
