### ISSUE TITLE
Add meanings and suggested courses of action to errors

### ISSUE THREAD

**Issue by colindean** [stribika/sshlabs#5]
When I run `scanner.py` against a server, I get this in the output:

```
ERROR! small DH group: 1024 bits, DHGEXGroup(prime=0xd9277daa27db131c03b108d41a76b4da8aceecccae73d2e48cedaaa70b09ef9f04fb020dcf36c51b8e485b26fabe0337e24232be4f4e693548310244937433fb1a5758195dc73b84adef8237472c46747d79dc0a2cf8a57ce8dbd8f466a20f8551e7b1b824b2e4987a8816d9bc0741c2798f3ebad3adebcc78fce6a772460c3f, generator=0x5)
```

I'm not really sure what this means. I tried regenerating my server's host key with 4096 bit (`sudo ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key`) but I still see the error message.

**Comment by stribika** [comment]
It means your server supports diffie-hellmann-group-exchange-sha\* and at least one of the groups in /etc/ssh/moduli are too small. Try this

```
ssh-keygen -G /etc/ssh/moduli.all -b 4096
ssh-keygen -T /etc/ssh/moduli.safe -f /etc/ssh/moduli.all
mv /etc/ssh/moduli.safe /etc/ssh/moduli
rm /etc/ssh/moduli.all
```

**Comment by stribika** [comment]
I should probably look into adding detailed description and instructions to the Issue class.

**Comment by stribika** [comment]
The new options --details and --instructions should now work.

**Comment by colindean** [comment]
If you put in the `ssh-keygen` instructions from above, you might want to warn that they will take a long time.

```
Tue May 24 11:42:39 2016 Found 34 safe primes of 184643 candidates in 47202 seconds
```

47202/60/60 ~= 13.1 hrs on a dual-core Intel Core 2 6600 @ 2.40GHz.
